services:
  - type: web
    name: tss-group-4-iot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
